# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34307c50fdd6c403ee1d1edd39ce697e2236b61c63755ec41aa00454f65e2924d91a93f15fc8279a266c58d3680f3b4ba8c16ded2a243d5abcd0a18f422b9de3

test:
  secret_key_base: 6e5a1446312ed2a638b5210102c3ce0ed83ca9200fc95995eca6f9adc509d2432099bbe90201248a274f42c790f5d3aecdd35a8a508f364407da1ce5b1852823

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 34307c50fdd6c403ee1d1edd39ce697e2236b61c63755ec41aa00454f65e2924d91a93f15fc8279a266c58d3680f3b4ba8c16ded2a243d5abcd0a18f422b9de3
